import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  FlatList,
  Dimensions,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { EmojiCategory } from '../types/inputTypes';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
const EMOJI_SIZE = SCREEN_WIDTH / 8;
const RECENT_EMOJIS_KEY = '@emoji_history';
const MAX_RECENT_EMOJIS = 40;

interface EmojiPanelProps {
  onEmojiSelect: (emoji: string) => void;
}

export const EmojiPanel: React.FC<EmojiPanelProps> = ({ onEmojiSelect }) => {
  const [selectedCategory, setSelectedCategory] = useState('recent');
  const [recentEmojis, setRecentEmojis] = useState<string[]>([]);

  // Load recent emojis from storage
  useEffect(() => {
    loadRecentEmojis();
  }, []);

  const loadRecentEmojis = async () => {
    try {
      const stored = await AsyncStorage.getItem(RECENT_EMOJIS_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        setRecentEmojis(parsed);
      }
    } catch (error) {
      console.error('Failed to load recent emojis:', error);
    }
  };

  const saveRecentEmoji = async (emoji: string) => {
    try {
      // Remove emoji if it already exists
      const filtered = recentEmojis.filter(e => e !== emoji);

      // Add emoji to the beginning
      const updated = [emoji, ...filtered].slice(0, MAX_RECENT_EMOJIS);

      // Update state
      setRecentEmojis(updated);

      // Save to storage
      await AsyncStorage.setItem(RECENT_EMOJIS_KEY, JSON.stringify(updated));
    } catch (error) {
      console.error('Failed to save recent emoji:', error);
    }
  };

  const handleEmojiPress = useCallback(
    (emoji: string) => {
      onEmojiSelect(emoji);
      saveRecentEmoji(emoji);
    },
    [onEmojiSelect]
  );

  const emojiCategories: EmojiCategory[] = useMemo(
    () => [
      {
        id: 'recent',
        name: 'Recent',
        icon: '🕒',
        emojis: recentEmojis,
      },
      {
        id: 'smileys',
        name: 'Smileys',
        icon: '😀',
        emojis: [
          '😀',
          '😃',
          '😄',
          '😁',
          '😆',
          '😅',
          '🤣',
          '😂',
          '🙂',
          '🙃',
          '😉',
          '😊',
          '😇',
          '🥰',
          '😍',
          '🤩',
          '😘',
          '😗',
          '😚',
          '😙',
          '😋',
          '😛',
          '😜',
          '🤪',
          '😝',
          '🤑',
          '🤗',
          '🤭',
          '🤫',
          '🤔',
          '🤐',
          '🤨',
          '😐',
          '😑',
          '😶',
          '😏',
          '😒',
          '🙄',
          '😬',
          '🤥',
          '😌',
          '😔',
          '😪',
          '🤤',
          '😴',
          '😷',
          '🤒',
          '🤕',
          '🤢',
          '🤮',
          '🤧',
          '🥵',
          '🥶',
          '🥴',
          '😵',
          '🤯',
          '🤠',
          '🥳',
          '😎',
          '🤓',
          '🧐',
          '😕',
          '😟',
          '🙁',
          '😮',
          '😯',
          '😲',
          '😳',
          '🥺',
          '😦',
          '😧',
          '😨',
          '😰',
          '😥',
          '😢',
          '😭',
          '😱',
          '😖',
          '😣',
          '😞',
        ],
      },
      {
        id: 'people',
        name: 'People',
        icon: '👋',
        emojis: [
          '👋',
          '🤚',
          '🖐',
          '✋',
          '🖖',
          '👌',
          '🤏',
          '✌',
          '🤞',
          '🤟',
          '🤘',
          '🤙',
          '👈',
          '👉',
          '👆',
          '🖕',
          '👇',
          '☝',
          '👍',
          '👎',
          '✊',
          '👊',
          '🤛',
          '🤜',
          '👏',
          '🙌',
          '👐',
          '🤲',
          '🤝',
          '🙏',
          '✍',
          '💅',
          '🤳',
          '💪',
          '🦾',
          '🦿',
          '🦵',
          '🦶',
          '👂',
          '🦻',
          '👃',
          '🧠',
          '🦷',
          '🦴',
          '👀',
          '👁',
          '👅',
          '👄',
          '💋',
          '🩸',
        ],
      },
      {
        id: 'animals',
        name: 'Animals',
        icon: '🐶',
        emojis: [
          '🐶',
          '🐱',
          '🐭',
          '🐹',
          '🐰',
          '🦊',
          '🐻',
          '🐼',
          '🐨',
          '🐯',
          '🦁',
          '🐮',
          '🐷',
          '🐽',
          '🐸',
          '🐵',
          '🙈',
          '🙉',
          '🙊',
          '🐒',
          '🐔',
          '🐧',
          '🐦',
          '🐤',
          '🐣',
          '🐥',
          '🦆',
          '🦅',
          '🦉',
          '🦇',
          '🐺',
          '🐗',
          '🐴',
          '🦄',
          '🐝',
          '🐛',
          '🦋',
          '🐌',
          '🐞',
          '🐜',
          '🦟',
          '🦗',
          '🕷',
          '🕸',
          '🦂',
          '🐢',
          '🐍',
          '🦎',
          '🦖',
          '🦕',
          '🐙',
          '🦑',
          '🦐',
          '🦞',
          '🦀',
          '🐡',
          '🐠',
          '🐟',
          '🐬',
          '🐳',
          '🐋',
          '🦈',
          '🐊',
          '🐅',
        ],
      },
      {
        id: 'food',
        name: 'Food',
        icon: '🍕',
        emojis: [
          '🍏',
          '🍎',
          '🍐',
          '🍊',
          '🍋',
          '🍌',
          '🍉',
          '🍇',
          '🍓',
          '🍈',
          '🍒',
          '🍑',
          '🥭',
          '🍍',
          '🥥',
          '🥝',
          '🍅',
          '🍆',
          '🥑',
          '🥦',
          '🥬',
          '🥒',
          '🌶',
          '🌽',
          '🥕',
          '🥔',
          '🍠',
          '🥐',
          '🥯',
          '🍞',
          '🥖',
          '🥨',
          '🧀',
          '🥚',
          '🍳',
          '🧈',
          '🥞',
          '🧇',
          '🥓',
          '🥩',
          '🍗',
          '🍖',
          '🌭',
          '🍔',
          '🍟',
          '🍕',
          '🥪',
          '🥙',
          '🧆',
          '🌮',
          '🌯',
          '🥗',
          '🥘',
          '🥫',
          '🍝',
          '🍜',
          '🍲',
          '🍛',
          '🍣',
          '🍱',
          '🥟',
          '🦪',
          '🍤',
          '🍙',
        ],
      },
      {
        id: 'activities',
        name: 'Activities',
        icon: '⚽',
        emojis: [
          '⚽',
          '🏀',
          '🏈',
          '⚾',
          '🥎',
          '🎾',
          '🏐',
          '🏉',
          '🥏',
          '🎱',
          '🪀',
          '🏓',
          '🏸',
          '🏒',
          '🏑',
          '🥍',
          '🏏',
          '🥅',
          '⛳',
          '🪁',
          '🏹',
          '🎣',
          '🤿',
          '🥊',
          '🥋',
          '🎽',
          '🛹',
          '🛷',
          '⛸',
          '🥌',
          '🎿',
          '⛷',
          '🏂',
          '🪂',
          '🏋',
          '🤼',
          '🤸',
          '🤺',
          '🤾',
          '🏌',
          '🏇',
          '🧘',
          '🏊',
          '🤽',
          '🚣',
          '🧗',
          '🚴',
          '🚵',
          '🎪',
          '🎭',
          '🎨',
          '🎬',
          '🎤',
          '🎧',
          '🎼',
          '🎹',
          '🥁',
          '🎷',
          '🎺',
          '🎸',
          '🪕',
          '🎻',
          '🎲',
          '♟',
        ],
      },
      {
        id: 'travel',
        name: 'Travel',
        icon: '✈️',
        emojis: [
          '🚗',
          '🚕',
          '🚙',
          '🚌',
          '🚎',
          '🏎',
          '🚓',
          '🚑',
          '🚒',
          '🚐',
          '🚚',
          '🚛',
          '🚜',
          '🦯',
          '🦽',
          '🦼',
          '🛴',
          '🚲',
          '🛵',
          '🏍',
          '🛺',
          '🚨',
          '🚔',
          '🚍',
          '🚘',
          '🚖',
          '🚡',
          '🚠',
          '🚟',
          '🚃',
          '🚋',
          '🚞',
          '🚝',
          '🚄',
          '🚅',
          '🚈',
          '🚂',
          '🚆',
          '🚇',
          '🚊',
          '🚉',
          '✈',
          '🛫',
          '🛬',
          '🛩',
          '💺',
          '🛰',
          '🚀',
          '🛸',
          '🚁',
          '🛶',
          '⛵',
          '🚤',
          '🛥',
          '🛳',
          '⛴',
          '🚢',
          '⚓',
          '⛽',
          '🚧',
          '🚦',
          '🚥',
          '🗺',
          '🗿',
        ],
      },
      {
        id: 'objects',
        name: 'Objects',
        icon: '💡',
        emojis: [
          '⌚',
          '📱',
          '📲',
          '💻',
          '⌨',
          '🖥',
          '🖨',
          '🖱',
          '🖲',
          '🕹',
          '🗜',
          '💽',
          '💾',
          '💿',
          '📀',
          '📼',
          '📷',
          '📸',
          '📹',
          '🎥',
          '📽',
          '🎞',
          '📞',
          '☎',
          '📟',
          '📠',
          '📺',
          '📻',
          '🎙',
          '🎚',
          '🎛',
          '🧭',
          '⏱',
          '⏲',
          '⏰',
          '🕰',
          '⌛',
          '⏳',
          '📡',
          '🔋',
          '🔌',
          '💡',
          '🔦',
          '🕯',
          '🪔',
          '🧯',
          '🛢',
          '💸',
          '💵',
          '💴',
          '💶',
          '💷',
          '💰',
          '💳',
          '💎',
          '⚖',
          '🧰',
          '🔧',
          '🔨',
          '⚒',
          '🛠',
          '⛏',
          '🔩',
          '⚙',
        ],
      },
      {
        id: 'symbols',
        name: 'Symbols',
        icon: '❤️',
        emojis: [
          '❤',
          '🧡',
          '💛',
          '💚',
          '💙',
          '💜',
          '🖤',
          '🤍',
          '🤎',
          '💔',
          '❣',
          '💕',
          '💞',
          '💓',
          '💗',
          '💖',
          '💘',
          '💝',
          '💟',
          '☮',
          '✝',
          '☪',
          '🕉',
          '☸',
          '✡',
          '🔯',
          '🕎',
          '☯',
          '☦',
          '🛐',
          '⛎',
          '♈',
          '♉',
          '♊',
          '♋',
          '♌',
          '♍',
          '♎',
          '♏',
          '♐',
          '♑',
          '♒',
          '♓',
          '🆔',
          '⚛',
          '🉑',
          '☢',
          '☣',
          '📴',
          '📳',
          '🈶',
          '🈚',
          '🈸',
          '🈺',
          '🈷',
          '✴',
          '🆚',
          '💮',
          '🉐',
          '㊙',
          '㊗',
          '🈴',
          '🈵',
          '🈹',
        ],
      },
      {
        id: 'flags',
        name: 'Flags',
        icon: '🏁',
        emojis: [
          '🏁',
          '🚩',
          '🎌',
          '🏴',
          '🏳',
          '🏳️‍🌈',
          '🏳️‍⚧️',
          '🏴‍☠️',
          '🇦🇨',
          '🇦🇩',
          '🇦🇪',
          '🇦🇫',
          '🇦🇬',
          '🇦🇮',
          '🇦🇱',
          '🇦🇲',
          '🇦🇴',
          '🇦🇶',
          '🇦🇷',
          '🇦🇸',
          '🇦🇹',
          '🇦🇺',
          '🇦🇼',
          '🇦🇽',
          '🇦🇿',
          '🇧🇦',
          '🇧🇧',
          '🇧🇩',
          '🇧🇪',
          '🇧🇫',
          '🇧🇬',
          '🇧🇭',
          '🇧🇮',
          '🇧🇯',
          '🇧🇱',
          '🇧🇲',
          '🇧🇳',
          '🇧🇴',
          '🇧🇶',
          '🇧🇷',
          '🇧🇸',
          '🇧🇹',
          '🇧🇻',
          '🇧🇼',
          '🇧🇾',
          '🇧🇿',
          '🇨🇦',
          '🇨🇨',
          '🇨🇩',
          '🇨🇫',
          '🇨🇬',
          '🇨🇭',
          '🇨🇮',
          '🇨🇰',
          '🇨🇱',
          '🇨🇲',
          '🇨🇳',
          '🇨🇴',
          '🇨🇵',
          '🇨🇷',
          '🇨🇺',
          '🇨🇻',
          '🇨🇼',
          '🇨🇽',
        ],
      },
    ],
    [recentEmojis]
  );

  const selectedCategoryData = emojiCategories.find(
    cat => cat.id === selectedCategory
  );

  const renderEmoji = ({ item }: { item: string }) => (
    <TouchableOpacity
      style={styles.emojiButton}
      onPress={() => handleEmojiPress(item)}>
      <Text style={styles.emoji}>{item}</Text>
    </TouchableOpacity>
  );

  return (
    <View style={styles.container}>
      {/* Emoji Grid */}
      <View style={styles.emojiContainer}>
        {selectedCategoryData && selectedCategoryData.emojis.length > 0 ? (
          <FlatList
            data={selectedCategoryData.emojis}
            renderItem={renderEmoji}
            keyExtractor={(item, index) => `${item}-${index}`}
            numColumns={8}
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.emojiGrid}
          />
        ) : (
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>No recent emojis</Text>
            <Text style={styles.emptySubtext}>
              Your recently used emojis will appear here
            </Text>
          </View>
        )}
      </View>

      {/* Category Tabs */}
      <View style={styles.tabBar}>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.tabContainer}>
          {emojiCategories.map(category => (
            <TouchableOpacity
              key={category.id}
              style={[
                styles.tab,
                selectedCategory === category.id && styles.activeTab,
              ]}
              onPress={() => setSelectedCategory(category.id)}>
              <Text style={styles.tabIcon}>{category.icon}</Text>
            </TouchableOpacity>
          ))}
        </ScrollView>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    height: 300,
    backgroundColor: '#0B141A',
  },
  emojiContainer: {
    flex: 1,
    backgroundColor: '#0B141A',
  },
  emojiGrid: {
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  emojiButton: {
    width: EMOJI_SIZE,
    height: EMOJI_SIZE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emoji: {
    fontSize: 28,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyText: {
    color: '#8696A0',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  emptySubtext: {
    color: '#667781',
    fontSize: 14,
    textAlign: 'center',
  },
  tabBar: {
    borderTopWidth: 1,
    borderTopColor: '#1C2C33',
    backgroundColor: '#0B141A',
  },
  tabContainer: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginHorizontal: 4,
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: '#1C2C33',
  },
  tabIcon: {
    fontSize: 24,
  },
});
